name: Terraform CI/CD

on:
  push:
    branches:
      - main #trigger only for commits pushed on main branch
jobs:
  terraform-plan:
    name: terraform 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4









